create type public.user_role as enum ('student', 'president', 'teacher');
create type public.task_priority as enum ('Low', 'Medium', 'High');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  role public.user_role not null default 'student',
  created_at timestamptz not null default now()
);

create table public.subjects (
  id bigint generated by default as identity primary key,
  name text not null unique,
  color text not null,
  icon text,
  created_at timestamptz not null default now()
);

create table public.homework (
  id bigint generated by default as identity primary key,
  subject_id bigint references public.subjects(id) on delete set null,
  title text not null,
  description text,
  due_date date not null,
  due_time time,
  priority public.task_priority not null default 'Medium',
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz
);

create table public.homework_completion (
  homework_id bigint not null references public.homework(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  completed boolean not null default false,
  completed_at timestamptz,
  primary key (homework_id, user_id)
);

create table public.tests (
  id bigint generated by default as identity primary key,
  subject_id bigint references public.subjects(id) on delete set null,
  title text not null,
  test_date date not null,
  test_range text,
  location text,
  notes text,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz
);

create table public.reminders (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  reminder_date date not null,
  reminder_time time,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  archived_at timestamptz
);

create table public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  event_date date not null,
  event_time time,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  archived_at timestamptz
);

create table public.announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  author_id uuid not null references public.profiles(id),
  pinned boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz
);

create table public.anonymous_questions (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text,
  status text not null default 'Unanswered' check (status in ('Unanswered', 'Answered', 'Archived')),
  created_by uuid not null references public.profiles(id),
  answered_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  answered_at timestamptz
);

create index homework_due_date_idx on public.homework(due_date);
create index tests_test_date_idx on public.tests(test_date);
create index announcements_pinned_idx on public.announcements(pinned, created_at desc);
create index anonymous_questions_status_idx on public.anonymous_questions(status, created_at desc);

create or replace function public.current_user_role()
returns public.user_role
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)));
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.subjects enable row level security;
alter table public.homework enable row level security;
alter table public.homework_completion enable row level security;
alter table public.tests enable row level security;
alter table public.reminders enable row level security;
alter table public.events enable row level security;
alter table public.announcements enable row level security;
alter table public.anonymous_questions enable row level security;

create policy "authenticated users can read profiles" on public.profiles for select to authenticated using (true);
create policy "users can update own name" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
create policy "authenticated users can read subjects" on public.subjects for select to authenticated using (true);
create policy "staff can manage subjects" on public.subjects for all to authenticated using (public.current_user_role() in ('president', 'teacher')) with check (public.current_user_role() in ('president', 'teacher'));

create policy "authenticated users can read homework" on public.homework for select to authenticated using (archived_at is null);
create policy "staff can create homework" on public.homework for insert to authenticated with check (public.current_user_role() in ('president', 'teacher') and created_by = auth.uid());
create policy "staff can update homework" on public.homework for update to authenticated using (public.current_user_role() in ('president', 'teacher')) with check (public.current_user_role() in ('president', 'teacher'));
create policy "teachers can delete homework" on public.homework for delete to authenticated using (public.current_user_role() = 'teacher');

create policy "users can read own completion" on public.homework_completion for select to authenticated using (user_id = auth.uid());
create policy "users can insert own completion" on public.homework_completion for insert to authenticated with check (user_id = auth.uid());
create policy "users can update own completion" on public.homework_completion for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "users can delete own completion" on public.homework_completion for delete to authenticated using (user_id = auth.uid());

create policy "authenticated users can read tests" on public.tests for select to authenticated using (archived_at is null);
create policy "staff can manage tests" on public.tests for all to authenticated using (public.current_user_role() in ('president', 'teacher')) with check (public.current_user_role() in ('president', 'teacher'));
create policy "authenticated users can read reminders" on public.reminders for select to authenticated using (archived_at is null);
create policy "staff can manage reminders" on public.reminders for all to authenticated using (public.current_user_role() in ('president', 'teacher')) with check (public.current_user_role() in ('president', 'teacher'));
create policy "authenticated users can read events" on public.events for select to authenticated using (archived_at is null);
create policy "staff can manage events" on public.events for all to authenticated using (public.current_user_role() in ('president', 'teacher')) with check (public.current_user_role() in ('president', 'teacher'));
create policy "authenticated users can read announcements" on public.announcements for select to authenticated using (archived_at is null);
create policy "staff can manage announcements" on public.announcements for all to authenticated using (public.current_user_role() in ('president', 'teacher')) with check (public.current_user_role() in ('president', 'teacher'));

create policy "students can create anonymous questions" on public.anonymous_questions for insert to authenticated with check (created_by = auth.uid());
create policy "staff can read anonymous questions" on public.anonymous_questions for select to authenticated using (public.current_user_role() in ('president', 'teacher'));
create policy "staff can answer anonymous questions" on public.anonymous_questions for update to authenticated using (public.current_user_role() in ('president', 'teacher')) with check (public.current_user_role() in ('president', 'teacher'));

insert into public.subjects (name, color, icon) values
  ('Geometry', '#4f7cff', 'triangle'),
  ('Biology', '#36a269', 'dna'),
  ('English', '#a06bd8', 'book'),
  ('Spanish', '#d99527', 'globe')
on conflict (name) do nothing;
